In [1]:
import tensorflow as tf
from keras.models import load_model

Using TensorFlow backend.


In [2]:
classifier = load_model('/path/to/model/directory/iRSVPred2_model.h5')

In [3]:
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import sklearn.metrics as metrics
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

In [14]:
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np
img1 = image.load_img('/image/path/image.jpg', target_size=(299, 299))
img = image.img_to_array(img1)
img = img/255
# create a batch of size 1 [N,H,W,C]
img = np.expand_dims(img, axis=0)
prediction = classifier.predict(img, batch_size=None,steps=1) #gives all class prob.
print(prediction)

[[9.9999893e-01 3.8615294e-08 4.7219748e-09 9.4768982e-10 2.6452197e-08
  1.5295056e-08 1.0054850e-06 3.1013709e-08 1.6366110e-10 1.2423714e-09
  6.0312209e-09]]


In [14]:
evaluation_data_dir= '/path/to/test/directory/'
evaluation_datagen = ImageDataGenerator(rescale=1./255)

evaluation_generator = evaluation_datagen.flow_from_directory(evaluation_data_dir,target_size=(img_rows,img_cols),
                                                              batch_size=batch_size,
                                                              classes=['1121','1509','1637','1718','1728','BAS_370','CSR_30','DHBT_3','PB1','PB_6','Unknown'],
                                                   class_mode='categorical', shuffle = False)
true_classes = evaluation_generator.classes
class_labels = list(evaluation_generator.class_indices)   

class_labels

target_names = ['1121','1509','1637','1718','1728','BAS_370','CSR_30','DHBT_3','PB1','PB_6','Unknown']
Y_pred = classifier.predict_generator(evaluation_generator, 19260 // batch_size+1)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
cm = metrics.confusion_matrix(evaluation_generator.classes, y_pred)
print(cm)
print('Classification Report')
print(metrics.classification_report(evaluation_generator.classes, y_pred))

Found 19260 images belonging to 11 classes.
Confusion Matrix
[[1473   14    0   11    2    0    0    0    0    0    0]
 [   1 1496    0    3    0    0    0    0    0    0    0]
 [   0    0 1330    0   21    0    3    0  126   20    0]
 [  71   48    0 1381    0    0    0    0    0    0    0]
 [ 105   29    0   67 1293    0    6    0    0    0    0]
 [   0    0    0    0    0 1500    0    0    0    0    0]
 [   0    0    0    0    0    0 1496    0    2    2    0]
 [   0    0    0    0    0    0    0 1500    0    0    0]
 [   0    0    1    0    0    0    1    0 1498    0    0]
 [   0    0   37    0    0    0   36    0   31 1396    0]
 [   0    0    0    1    1    0    0    0   15    1 4242]]
Classification Report
              precision    recall  f1-score   support

           0       0.89      0.98      0.94      1500
           1       0.94      1.00      0.97      1500
           2       0.97      0.89      0.93      1500
           3       0.94      0.92      0.93      1500
       